const products = [
  {
    id: 1,
    name: "Ergonomic Mouse Pad",
    rating: 5,
    numberOfBuyers: 256,
    discountRate: 15,
    discountUpTo: "2025-01-31T23:59:59",
    isNewProduct: true,
    image: "mouse-pad.jpg",
    description:
      "Experience unparalleled comfort and precision with our ergonomic mouse pad...",
    isOnFlashSale: true,
    flashSaleUpTo: "2025-01-31T23:59:59",
  },
  {
    id: 2,
    name: "Sporty Sneakers",
    rating: 4,
    numberOfBuyers: 500,
    discountRate: 20,
    discountUpTo: "2025-01-25T23:59:59",
    isNewProduct: false,
    image: "shoe.jpg",
    description:
      "Step into style and comfort with our trendy sporty sneakers...",
    isOnFlashSale: false,
    flashSaleUpTo: "2025-01-31T23:59:59",
  },
  {
    id: 3,
    name: "Wireless Headphones",
    rating: 3,
    numberOfBuyers: 320,
    discountRate: 10,
    discountUpTo: "2025-02-10T23:59:59",
    isNewProduct: true,
    image: "headphone.jpg",
    description:
      "Immerse yourself in high-definition sound with our premium wireless headphones...",
    isOnFlashSale: true,
    flashSaleUpTo: "2025-01-31T23:59:59",
  },
  {
    id: 4,
    name: "Mechanical Keyboard",
    rating: 4,
    numberOfBuyers: 450,
    discountRate: 25,
    discountUpTo: "2025-02-05T23:59:59",
    isNewProduct: false,
    image: "keyboard.png",
    description:
      "Experience precision typing like never before with our mechanical keyboard...",
    isOnFlashSale: false,
    flashSaleUpTo: "2025-01-31T23:59:59",
  },
  {
    id: 5,
    name: "Classic Cotton T-Shirt",
    rating: 5,
    numberOfBuyers: 300,
    discountRate: 30,
    discountUpTo: "2025-01-28T23:59:59",
    isNewProduct: true,
    image: "tshirt.jpg",
    description: "Upgrade your wardrobe with our classic cotton t-shirt...",
    isOnFlashSale: true,
    flashSaleUpTo: "2025-01-31T23:59:59",
  },
  {
    id: 6,
    name: "Mountain Bicycle",
    rating: 3,
    numberOfBuyers: 150,
    discountRate: 18,
    discountUpTo: "2025-02-12T23:59:59",
    isNewProduct: false,
    image: "bicycle.jpg",
    description: "Conquer trails and city streets with our mountain bicycle...",
    isOnFlashSale: false,
    flashSaleUpTo: "2025-01-31T23:59:59",
  },
  {
    id: 7,
    name: "Wireless Gaming Mouse",
    rating: 4,
    numberOfBuyers: 220,
    discountRate: 15,
    discountUpTo: "2025-01-30T23:59:59",
    isNewProduct: true,
    image: "mouse.jpg",
    description:
      "Dominate your game with precision and speed using our wireless gaming mouse...",
    isOnFlashSale: true,
    flashSaleUpTo: "2025-01-31T23:59:59",
  },
  {
    id: 8,
    name: "Elegant Bowl Set",
    rating: 5,
    numberOfBuyers: 180,
    discountRate: 12,
    discountUpTo: "2025-02-07T23:59:59",
    isNewProduct: false,
    image: "bowl-set.jpg",
    description: "Elevate your dining experience with our elegant bowl set...",
    isOnFlashSale: false,
    flashSaleUpTo: "2025-01-31T23:59:59",
  },
];
