export const products = [
  {
    id: 1,
    name: "Ergonomic Mouse Pad",
    slug: "ergonomic-mouse-pad",
    price: 500,
    rating: 5,
    numberOfBuyers: 256,
    discountRate: 15,
    discountUpTo: "2025-01-31T23:59:59",
    isNewProduct: true,
    image: "mouse-pad.jpg",
    variants: [
      "https://m.media-amazon.com/images/I/71z2DcD8DGL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61L4R92hAqL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71fNy4l6Q-L._AC_SL1500_.jpg",
    ],
    description:
      "Experience unparalleled comfort and precision with our ergonomic mouse pad...",
    isOnFlashSale: true,
    flashSaleUpTo: "2025-01-31T23:59:59",
  },
  {
    id: 2,
    name: "Sporty Sneakers",
    slug: "sporty-sneakers",
    price: 4000,
    rating: 4,
    numberOfBuyers: 500,
    discountRate: 20,
    discountUpTo: "2025-01-25T23:59:59",
    isNewProduct: false,
    image: "shoe.jpg",
    variants: [
      "https://m.media-amazon.com/images/I/71Y0cnkp3rL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71YK20XjSNL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71n8-fpWq6L._AC_SL1500_.jpg",
    ],
    description:
      "Step into style and comfort with our trendy sporty sneakers...",
    isOnFlashSale: false,
    flashSaleUpTo: "2025-01-31T23:59:59",
  },
  {
    id: 3,
    name: "Wireless Headphones",
    slug: "wireless-headphones",
    price: 3500,
    rating: 3,
    numberOfBuyers: 320,
    discountRate: 10,
    discountUpTo: "2025-02-10T23:59:59",
    isNewProduct: true,
    image: "headphone.jpg",
    variants: [
      "https://m.media-amazon.com/images/I/61djv8PhV8L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71jG+e7roXL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71kLLFxUshL._AC_SL1500_.jpg",
    ],
    description:
      "Immerse yourself in high-definition sound with our premium wireless headphones...",
    isOnFlashSale: true,
    flashSaleUpTo: "2025-01-31T23:59:59",
  },
  {
    id: 4,
    name: "Mechanical Keyboard",
    slug: "mechanical-keyboard",
    price: 8000,
    rating: 4,
    numberOfBuyers: 450,
    discountRate: 25,
    discountUpTo: "2025-02-05T23:59:59",
    isNewProduct: false,
    image: "keyboard.png",
    variants: [
      "https://m.media-amazon.com/images/I/71Vmtq1pXkL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61G5pH4uB8L._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71J2CJinlFL._AC_SL1500_.jpg",
    ],
    description:
      "Experience precision typing like never before with our mechanical keyboard...",
    isOnFlashSale: false,
    flashSaleUpTo: "2025-01-31T23:59:59",
  },
  {
    id: 5,
    name: "Classic Cotton T-Shirt",
    slug: "classic-cotton-t-shirt",
    price: 1000,
    rating: 5,
    numberOfBuyers: 300,
    discountRate: 30,
    discountUpTo: "2025-01-28T23:59:59",
    isNewProduct: true,
    image: "tshirt.jpg",
    variants: [
      "https://m.media-amazon.com/images/I/51d5w1z-CFL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61Bq5qnlFlL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61P0bD-KmsL._AC_SL1500_.jpg",
    ],
    description: "Upgrade your wardrobe with our classic cotton t-shirt...",
    isOnFlashSale: true,
    flashSaleUpTo: "2025-01-31T23:59:59",
  },
  {
    id: 6,
    name: "Mountain Bicycle",
    slug: "mountain-bicycle",
    price: 20000,
    rating: 3,
    numberOfBuyers: 150,
    discountRate: 18,
    discountUpTo: "2025-02-12T23:59:59",
    isNewProduct: false,
    image: "bicycle.jpg",
    variants: [
      "https://m.media-amazon.com/images/I/81tNsmfJhPL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71Ku-RNwzFL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71OfUAWey6L._AC_SL1500_.jpg",
    ],
    description: "Conquer trails and city streets with our mountain bicycle...",
    isOnFlashSale: false,
    flashSaleUpTo: "2025-01-31T23:59:59",
  },
  {
    id: 7,
    name: "Wireless Gaming Mouse",
    slug: "wireless-gaming-mouse",
    price: 2500,
    rating: 4,
    numberOfBuyers: 220,
    discountRate: 15,
    discountUpTo: "2025-01-30T23:59:59",
    isNewProduct: true,
    image: "mouse.jpg",
    variants: [
      "https://m.media-amazon.com/images/I/61IoEAEoHYL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61nn7nfHLgL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61YcuN7PCfL._AC_SL1500_.jpg",
    ],
    description:
      "Dominate your game with precision and speed using our wireless gaming mouse...",
    isOnFlashSale: true,
    flashSaleUpTo: "2025-01-31T23:59:59",
  },
  {
    id: 8,
    name: "Elegant Bowl Set",
    slug: "elegant-bowl-set",
    price: 2500,
    rating: 5,
    numberOfBuyers: 180,
    discountRate: 12,
    discountUpTo: "2025-02-07T23:59:59",
    isNewProduct: false,
    image: "bowl-set.jpg",
    variants: [
      "https://m.media-amazon.com/images/I/71D-BmfYtPL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/61P8tRtuvzL._AC_SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71iMek6wR9L._AC_SL1500_.jpg",
    ],
    description: "Elevate your dining experience with our elegant bowl set...",
    isOnFlashSale: false,
    flashSaleUpTo: "2025-01-31T23:59:59",
  },
];
